export const INITTOPBANNER = 'RECOMMEND_INITTOPBANNER';
export const INITHOTRECOMMEND = 'RECOMMEND_INITHOTRECOMMEND';
export const INITNEWALBUM = 'RECOMMEND_INITNEWALBUM';
export const INITUPRANKING = 'RECOMMEND_INITUPRANKING';
export const INITNEWRANKING = 'RECOMMEND_INITNEWRANKING';
export const INITORIGINRANKING = 'RECOMMEND_INITORIGINRANKING';