export const INITPLAYSONG = 'PLAYER_INITPLAYSONG';
export const CHANGEPLAYLIST = 'PLAYER_CHANGEPLAYLIST';
export const CHANGEPLAYOPTIONS = 'PLAYER_CHANGEPLAYOPTIONS';
export const CHANGECURRENTSONGINDEX = 'PLAYER_CHANGECURRENTSONGINDEX';
export const CHANGELYRICS = 'PLAYER_CHANGELYRICS';